twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
    globals:
        app_supported_locales: '%app.supported_locales%'

when@test:
    twig:
        strict_variables: true
